import { ReactElement } from 'react';
import Head from 'next/head';

import GuessLayout from '../../layouts/guess';

const SignUpTemplate = (): ReactElement => {
  return (
    <div>
      <Head>
        <title>Sign Up Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Sign Up</h1>
      </main>
    </div>
  );
};

const SignUpPage = (): ReactElement => {
  return <GuessLayout Component={SignUpTemplate} />;
};

export default SignUpPage;
