import { ReactElement } from 'react';
import Head from 'next/head';

import AuthLayout from '../../layouts/auth';

const SignInTemplate = (): ReactElement => {
  return (
    <div>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Sign In</h1>
      </main>
    </div>
  );
};

const SignInPage = (): ReactElement => {
  return <AuthLayout Component={SignInTemplate} />;
};

export default SignInPage;
