import { ReactElement } from 'react';
import Head from 'next/head';
import { Input, Button } from '@parley-hub/grace';

import GuessLayout from '../../layouts/guess';

const SignInTemplate = (): ReactElement => {
  return (
    <>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-gray-100 py-10 md:py-20 full-screen flex items-center">
        <div className="container">
          <div className="grid grid-cols-12 gap-8">
            <div className="col-span-4 col-start-5">
              <Input
                className="mb-4"
                placeholder="Email"
                type="text"
                inputSize="large"
                fullWidth
              />

              <Input
                className="mb-4"
                placeholder="Password"
                type="password"
                inputSize="large"
                fullWidth
              />

              <Button label="Sign In" variant="info" size="large" fullWidth />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

const SignInPage = (): ReactElement => {
  return <GuessLayout Component={SignInTemplate} />;
};

export default SignInPage;
