import { ReactElement } from 'react';
import Head from 'next/head';

import AuthLayout from '../../layouts/auth';

const DashboardTemplate = (): ReactElement => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-lightest-gray py-10 md:py-20 full-screen flex items-center">
        <div className="container">
          <h2>Dashboard</h2>
        </div>
      </main>
    </>
  );
};

const DashboardPage = (): ReactElement => {
  return <AuthLayout Component={DashboardTemplate} />;
};

export default DashboardPage;
