---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-deployment
  namespace: default
  labels:
    app: apollo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      imagePullSecrets:
        - name: apollo-secret
      containers:
        - name: apollo
          image: hiepnh610/apollo:0.0.1
          envFrom:
            - secretRef:
                name: apollo-secret
                optional: true
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.25"

---

apiVersion: v1
kind: Service
metadata:
  name: apollo-service
spec:
  type: ClusterIP
  selector:
    app: apollo
  ports:
    - name: apollo-port
      protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
  namespace: default
spec:
  tls:
    - hosts:
        - parley-hub.com
      secretName: apollo-secret-tls
  rules:
    - host: parley-hub.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apollo-service
                port:
                  number: 80
