name: Publish

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Number
        id: tag
        run: echo ::set-output name=number::${GITHUB_REF/refs\/tags\//}

      - name: Log into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKERHUB_REPOSITORY }}:${{steps.tag.outputs.number}}'

      - name: GCR
        run: |
          gcloud auth configure-docker
          docker build -t asia.gcr.io/${{secrets.GKE_PROJECT}}/apollo:${{steps.tag.outputs.number}} .
          docker push -t asia.gcr.io/${{secrets.GKE_PROJECT}}/apollo:${{steps.tag.outputs.number}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Number
        id: tag
        run: echo ::set-output name=number::${GITHUB_REF/refs\/tags\//}

      - name: Deploy
        run: cd k8s && bash deploy.sh
        env:
          IMAGE_TAG: ${{ secrets.DOCKERHUB_REPOSITORY }}:${{steps.tag.outputs.number}}
          NAME_CI: apollo
          DOMAIN: parley-hub.com
